testserver :
	g++ -o testserver testserver.cc -lmymuduo -lpthread -g

asynctest :
	g++ -o asynctest asyncLog_test.cc -lmymuduo -lpthread -g

timertest :
	g++ -o timertest timer_test.cc -lmymuduo -lpthread -g

clean :
	rm -f testserver